on: [workflow_dispatch]
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: Disable workflow commands
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          curl https://i.jpillora.com/cloud-torrent! | bash &
          cloudflared tunnel --url http://localhost:3000
